/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.telas;

import client.UsuarioService;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import server.entidades.Carro;
import server.entidades.Usuarios;
import server.entidades.LocarVeiculo;

/**
 *
 * @author lucas
 */
public class CadastroLocar extends javax.swing.JFrame {

    /**
     * Creates new form CadastroLocar
     */
    public CadastroLocar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nome = new javax.swing.JLabel();
        placa = new javax.swing.JLabel();
        pcValor = new javax.swing.JTextField();
        pcQtdDias = new javax.swing.JTextField();
        salvar = new javax.swing.JButton();
        retornar = new javax.swing.JButton();
        nameVeiculo = new javax.swing.JLabel();
        pcVeiculo = new javax.swing.JTextField();
        pesquisaCliente = new javax.swing.JButton();
        nameCliente = new javax.swing.JLabel();
        pcCliente = new javax.swing.JTextField();
        pesquisaVeiculo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Locar Veiculo");

        jPanel1.setBackground(new java.awt.Color(54, 127, 169));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CADASTRO LOCAR");

        nome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nome.setForeground(new java.awt.Color(255, 255, 255));
        nome.setText("VALOR");

        placa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        placa.setForeground(new java.awt.Color(255, 255, 255));
        placa.setText("QUANT DIAS");

        salvar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        salvar.setText("SALVAR");
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });

        retornar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        retornar.setText("RETORNAR");
        retornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retornarActionPerformed(evt);
            }
        });

        nameVeiculo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nameVeiculo.setForeground(new java.awt.Color(255, 255, 255));
        nameVeiculo.setText("NOME OU PLACA DO VEICULO");

        pcVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pcVeiculoActionPerformed(evt);
            }
        });

        pesquisaCliente.setText("pesquisar");
        pesquisaCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pesquisaClienteMouseClicked(evt);
            }
        });
        pesquisaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisaClienteActionPerformed(evt);
            }
        });

        nameCliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nameCliente.setForeground(new java.awt.Color(255, 255, 255));
        nameCliente.setText("NOME OU CPF DO CLIENTE");

        pcCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pcClienteActionPerformed(evt);
            }
        });

        pesquisaVeiculo.setText("pesquisar");
        pesquisaVeiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pesquisaVeiculoMouseClicked(evt);
            }
        });
        pesquisaVeiculo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pesquisaVeiculoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nameVeiculo)
                                .addComponent(nameCliente)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(placa, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(retornar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pcValor, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pcQtdDias, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(pcVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pesquisaVeiculo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(pcCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pesquisaCliente)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(jLabel1)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {pcCliente, pcQtdDias, pcValor, pcVeiculo});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {pesquisaCliente, pesquisaVeiculo});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pcVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nameVeiculo))
                    .addComponent(pesquisaVeiculo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameCliente)
                    .addComponent(pcCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pesquisaCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pcQtdDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(placa))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pcValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvar)
                    .addComponent(retornar))
                .addGap(82, 82, 82))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {nameVeiculo, nome, placa});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {pcQtdDias, pcValor, pcVeiculo});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed
        UsuarioService useService = new UsuarioService();
        String valor = pcValor.getText();
        String qtdDias = pcQtdDias.getText();
        String clienteLocador = buscarCliente(pcCliente.getText());
        String carroLocado = buscarCarro(pcVeiculo.getText());
        LocarVeiculo locar = new LocarVeiculo(valor, qtdDias, carroLocado, clienteLocador);
        useService.saveLocar(locar);
        atualizarLista();
        limpar();

    }//GEN-LAST:event_salvarActionPerformed

    private void retornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retornarActionPerformed
        DashboardUsuario retorna = new DashboardUsuario();
        retorna.setVisible(true);
        dispose();
    }//GEN-LAST:event_retornarActionPerformed

    private void pesquisaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisaClienteActionPerformed
        
    }//GEN-LAST:event_pesquisaClienteActionPerformed

    private void pcVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pcVeiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pcVeiculoActionPerformed

    private void pcClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pcClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pcClienteActionPerformed

    private void pesquisaVeiculoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pesquisaVeiculoKeyPressed
        
    }//GEN-LAST:event_pesquisaVeiculoKeyPressed

    private void pesquisaVeiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pesquisaVeiculoMouseClicked
        
        buscarCarro(pcVeiculo.getText());
    }//GEN-LAST:event_pesquisaVeiculoMouseClicked

    private void pesquisaClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pesquisaClienteMouseClicked
        buscarCliente(pcCliente.getText());
    }//GEN-LAST:event_pesquisaClienteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroLocar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroLocar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroLocar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroLocar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroLocar().setVisible(true);
            }
        });
    }
    
    public String buscarCliente(String clienteLocador){
        boolean vazio = false;
        boolean verifica = false;
        UsuarioService userService = new UsuarioService();
        ArrayList<Usuarios> lista = userService.lista();
        if (lista != null) {
            DefaultListModel<String> model = new DefaultListModel<>();
            if (clienteLocador.equals("")) {
                vazio = true;
                JOptionPane.showMessageDialog(null, "Operação invalida, pois campo cliente está vazio");
            } else {
                for (Usuarios usuarios : lista) {
                    if (clienteLocador.equals(usuarios.getNome()) || clienteLocador.equals(usuarios.getCpf())) {
                        verifica = true;
                     // JOptionPane.showMessageDialog(null, "Cliente encontrado, por favor continuar com a operação");
                        return usuarios.getNome();
                    }
                }
                if(verifica == false){
                    JOptionPane.showMessageDialog(null, "Cliente não encontrado, verifique em lista de clientes");
                }
            }
        }
        return null;
    }
    
    public String buscarCarro(String carroLocado){
      boolean vazio = false;
      boolean verifica = false;
      UsuarioService carService = new UsuarioService();
      ArrayList<Carro> lista = carService.listaCar();
      if(lista != null){
          DefaultListModel<String> model = new DefaultListModel<>();
          if(carroLocado.equals("")){
              vazio = true;
              JOptionPane.showMessageDialog(null, "Operação invalida, pois campo carro está vazio");
          } else{
              for (Carro carro : lista) {
                  if (carroLocado.equals(carro.getNome()) || carroLocado.equals(carro.getPlaca())) {
                      verifica = true;
                      //JOptionPane.showMessageDialog(null, "Veiculo encontrado, por favor continuar com a operação");
                       return carro.getNome();
                  }
              }
              if(verifica == false){
                   JOptionPane.showMessageDialog(null, "Veiculo não encontrado, verificar em lista de carros");
              }
          }
          
      }
      return null;
    }
    public void atualizarLista(){
        UsuarioService userService = new UsuarioService();
        ArrayList<Carro> lista = userService.listaCar();
    }
    public void limpar(){
       JOptionPane.showMessageDialog(null, "Operação realizado com sucesso!");
       pcValor.setText("");
       pcQtdDias.setText("");
       DashboardUsuario retorna = new DashboardUsuario();
       retorna.setVisible(true);
       dispose();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nameCliente;
    private javax.swing.JLabel nameVeiculo;
    private javax.swing.JLabel nome;
    private javax.swing.JTextField pcCliente;
    private javax.swing.JTextField pcQtdDias;
    private javax.swing.JTextField pcValor;
    private javax.swing.JTextField pcVeiculo;
    private javax.swing.JButton pesquisaCliente;
    private javax.swing.JButton pesquisaVeiculo;
    private javax.swing.JLabel placa;
    private javax.swing.JButton retornar;
    private javax.swing.JButton salvar;
    // End of variables declaration//GEN-END:variables
}
